package com.paulina.dynamopractice.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

@Data
@DynamoDBTable(tableName = "Movie")
public class Movie {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    private String Id;

    @DynamoDBAttribute
    public String Title;

    @DynamoDBAttribute
    public String CreatedBy;

    @DynamoDBAttribute
    public String CreatedDate;

    @DynamoDBAttribute
    public String ModifiedDate;

    @DynamoDBAttribute
    public String ReleaseYear;
}
